/**
 * ============================================================================
 * МОДУЛЬ: utils/foodAndDrinkPresets.ts (21+ Видов Корма и 16 Видов Напитков)
 * ============================================================================
 * 
 * 🎓 АРХИТЕКТУРНОЕ ОБОСНОВАНИЕ:
 * Расширенная база продуктов и напитков:
 * - `FOOD_ITEMS`: 21 вид корма (зерновые смеси, орехи, овощи, фрукты, белок).
 * - `DRINK_ITEMS`: 16 напитков (родниковая вода, фреши, смузи, ягодные морсы).
 * Каждый напиток задает цвет жидкости (`liquidColor`), который отображается
 * в дизайнерских поилках в клетке.
 */

import { FoodItem, DrinkItem } from '@/types/hamster';

// ============================================================================
// 1. КОЛЛЕКЦИЯ 21 ВИДА КОРМА (FOOD_ITEMS)
// ============================================================================
export const FOOD_ITEMS: FoodItem[] = [
  {
    id: 'sunflower_seeds',
    name: 'Семечки подсолнуха',
    description: 'Хрустящие полосатые семечки. Любимая классика для набивания щечек.',
    icon: '🌻',
    hungerGain: 18,
    happinessGain: 12,
    healthGain: 3,
    eatingDurationSec: 3,
  },
  {
    id: 'grain_mix',
    name: 'Зерновой премиум-микс',
    description: 'Овсяные хлопья, просо, пшеница и канареечное семя. Сытный рацион.',
    icon: '🌾',
    hungerGain: 35,
    happinessGain: 15,
    healthGain: 6,
    eatingDurationSec: 5,
  },
  {
    id: 'apple_slice',
    name: 'Сочное яблоко',
    description: 'Свежий сладкий ломтик. Богат железом, отлично увлажняет и радует.',
    icon: '🍎',
    hungerGain: 22,
    happinessGain: 24,
    healthGain: 10,
    eatingDurationSec: 4,
  },
  {
    id: 'carrot_fresh',
    name: 'Молодая морковка',
    description: 'Хрустящий оранжевый корнеплод с бета-каротином для острых зубок.',
    icon: '🥕',
    hungerGain: 25,
    happinessGain: 20,
    healthGain: 12,
    eatingDurationSec: 4,
  },
  {
    id: 'strawberry_bite',
    name: 'Спелая земляничка',
    description: 'Ароматная лесная ягодка. Вызывает бурный восторг у хомячка!',
    icon: '🍓',
    hungerGain: 20,
    happinessGain: 35,
    healthGain: 14,
    eatingDurationSec: 3.5,
  },
  {
    id: 'walnut_crust',
    name: 'Грецкий орех',
    description: 'Питательное ядро в скорлупе. Источник полезных жиров и микроэлементов.',
    icon: '🌰',
    hungerGain: 38,
    happinessGain: 28,
    healthGain: 8,
    eatingDurationSec: 5,
  },
  {
    id: 'parmesan_cheese',
    name: 'Ломтик пармезана',
    description: 'Пикантный твердый сыр. Необыкновенно аппетитный белковый деликатес.',
    icon: '🧀',
    hungerGain: 30,
    happinessGain: 32,
    healthGain: 5,
    eatingDurationSec: 4,
  },
  {
    id: 'banana_chips',
    name: 'Банановые чипсы',
    description: 'Хрустящие сушеные ломтики банана. Сладкий заряд энергии.',
    icon: '🍌',
    hungerGain: 26,
    happinessGain: 30,
    healthGain: 6,
    eatingDurationSec: 4,
  },
  {
    id: 'fresh_lettuce',
    name: 'Лист салата и укроп',
    description: 'Свежая сочная зелень. Улучшает пищеварение и освежает.',
    icon: '🥬',
    hungerGain: 15,
    happinessGain: 18,
    healthGain: 15,
    eatingDurationSec: 3,
  },
  {
    id: 'sweet_corn',
    name: 'Сахарная кукуруза',
    description: 'Золотистые сладкие зерна. Хомячок обожает держать их в передних лапках.',
    icon: '🌽',
    hungerGain: 28,
    happinessGain: 22,
    healthGain: 7,
    eatingDurationSec: 4,
  },
  {
    id: 'drops_treat',
    name: 'Йогуртовые дропсы',
    description: 'Царское лакомство для грызунов. Нежнейший ягодный крем.',
    icon: '🍧',
    hungerGain: 40,
    happinessGain: 45,
    healthGain: 18,
    eatingDurationSec: 5,
  },
  {
    id: 'pumpkin_seeds',
    name: 'Тыквенные семечки',
    description: 'Крупные белые семечки с цинком. Укрепляют шерстку и иммунитет.',
    icon: '🎃',
    hungerGain: 24,
    happinessGain: 20,
    healthGain: 14,
    eatingDurationSec: 4,
  },
  {
    id: 'protein_mealworm',
    name: 'Сушеный мучной червячок',
    description: 'Натуральный протеин высшей пробы. Дает зверьку первобытную силу.',
    icon: '🐛',
    hungerGain: 32,
    happinessGain: 25,
    healthGain: 16,
    eatingDurationSec: 4,
  },
  {
    id: 'roasted_peanut',
    name: 'Арахисовый орешек',
    description: 'Поджаренный орех без соли. Плотный перекус на целый день.',
    icon: '🥜',
    hungerGain: 30,
    happinessGain: 22,
    healthGain: 8,
    eatingDurationSec: 4.5,
  },
  {
    id: 'oat_cookie',
    name: 'Овсяное печенье',
    description: 'Домашняя злаковая выпечка без сахара с медовым ароматом.',
    icon: '🍪',
    hungerGain: 34,
    happinessGain: 26,
    healthGain: 7,
    eatingDurationSec: 5,
  },
  {
    id: 'apple_stick',
    name: 'Веточка яблони',
    description: 'Твердая древесная палочка для естественного стачивания резцов.',
    icon: '🪵',
    hungerGain: 10,
    happinessGain: 18,
    healthGain: 22,
    eatingDurationSec: 4,
  },
  {
    id: 'watermelon_slice',
    name: 'Ломтик арбуза',
    description: 'Сладкая сахарная мякоть. Идеально спасает от летней жары.',
    icon: '🍉',
    hungerGain: 20,
    happinessGain: 30,
    healthGain: 12,
    eatingDurationSec: 3.5,
  },
  {
    id: 'steamed_broccoli',
    name: 'Соцветие брокколи',
    description: 'Зеленый мини-кустик витаминов. Заботится о здоровье желудка.',
    icon: '🥦',
    hungerGain: 18,
    happinessGain: 16,
    healthGain: 20,
    eatingDurationSec: 3.5,
  },
  {
    id: 'cucumber_slice',
    name: 'Хрустящий огурчик',
    description: 'Тонкий освежающий кругляш. Дарит легкость и бодрость.',
    icon: '🥒',
    hungerGain: 14,
    happinessGain: 15,
    healthGain: 12,
    eatingDurationSec: 3,
  },
  {
    id: 'vitamin_pellet',
    name: 'Мультивитаминные гранулы',
    description: 'Специальные лечебные таблетки с кальцием и биотином.',
    icon: '💊',
    hungerGain: 20,
    happinessGain: 14,
    healthGain: 35,
    eatingDurationSec: 3,
  },
  {
    id: 'honey_cracker',
    name: 'Медовый крекер',
    description: 'Зерна, запеченные в цветочном меду на деревянном стержне.',
    icon: '🍯',
    hungerGain: 42,
    happinessGain: 38,
    healthGain: 10,
    eatingDurationSec: 5.5,
  },
];

// ============================================================================
// 2. КОЛЛЕКЦИЯ 16 ВИДОВ НАПИТКОВ И СОКОВ (DRINK_ITEMS)
// ============================================================================
export const DRINK_ITEMS: DrinkItem[] = [
  {
    id: 'fresh_water',
    name: 'Родниковая вода',
    description: 'Кристально чистая артезианская вода. Утоляет жажду и восстанавливает баланс.',
    icon: '💧',
    liquidColor: '#38bdf8',
    hungerGain: 5,
    energyGain: 15,
    happinessGain: 12,
    healthGain: 10,
    drinkingDurationSec: 3.5,
  },
  {
    id: 'carrot_juice',
    name: 'Морковный фреш',
    description: 'Свежевыжатый морковный сок. Заряжает энергией и обостряет зрение.',
    icon: '🥕',
    liquidColor: '#f97316',
    hungerGain: 12,
    energyGain: 25,
    happinessGain: 20,
    healthGain: 16,
    drinkingDurationSec: 4,
  },
  {
    id: 'apple_juice',
    name: 'Яблочный нектар',
    description: 'Осветленный сладкий сок из спелых яблок. Дарит мгновенную радость.',
    icon: '🍎',
    liquidColor: '#eab308',
    hungerGain: 10,
    energyGain: 22,
    happinessGain: 25,
    healthGain: 12,
    drinkingDurationSec: 4,
  },
  {
    id: 'strawberry_nectar',
    name: 'Клубничный смузи',
    description: 'Густой ароматный ягодный напиток. Максимум эндорфинов!',
    icon: '🍓',
    liquidColor: '#ef4444',
    hungerGain: 14,
    energyGain: 28,
    happinessGain: 35,
    healthGain: 14,
    drinkingDurationSec: 4.5,
  },
  {
    id: 'cucumber_water',
    name: 'Огуречный детокс',
    description: 'Прохладная вода с ломтиками огурца. Легкость и чистота.',
    icon: '🥒',
    liquidColor: '#22c55e',
    hungerGain: 6,
    energyGain: 18,
    happinessGain: 15,
    healthGain: 18,
    drinkingDurationSec: 3.5,
  },
  {
    id: 'watermelon_smoothie',
    name: 'Арбузный шейк',
    description: 'Ледяной фреш из сладкой сердцевины арбуза. Освежает до кончиков ушей.',
    icon: '🍉',
    liquidColor: '#f43f5e',
    hungerGain: 8,
    energyGain: 20,
    happinessGain: 30,
    healthGain: 12,
    drinkingDurationSec: 4,
  },
  {
    id: 'chamomile_tea',
    name: 'Ромашковый чай',
    description: 'Теплый отвар цветков аптечной ромашки. Успокаивает и готовит ко сну.',
    icon: '🌼',
    liquidColor: '#fbbf24',
    hungerGain: 4,
    energyGain: 12,
    happinessGain: 22,
    healthGain: 25,
    drinkingDurationSec: 4,
  },
  {
    id: 'blueberry_nectar',
    name: 'Черничный морс',
    description: 'Насыщенный темно-синий ягодный напиток. Защищает иммунитет.',
    icon: '🫐',
    liquidColor: '#6366f1',
    hungerGain: 10,
    energyGain: 24,
    happinessGain: 26,
    healthGain: 22,
    drinkingDurationSec: 4,
  },
  {
    id: 'banana_shake',
    name: 'Банановый шейк',
    description: 'Питательный густой коктейль. Дает мощный заряд энергии для бега в колесе.',
    icon: '🍌',
    liquidColor: '#fde047',
    hungerGain: 18,
    energyGain: 35,
    happinessGain: 24,
    healthGain: 10,
    drinkingDurationSec: 4.5,
  },
  {
    id: 'raspberry_compote',
    name: 'Малиновый компот',
    description: 'Сладкий бабушкин компот из дачной малины. Согревает душу.',
    icon: '🍧',
    liquidColor: '#ec4899',
    hungerGain: 12,
    energyGain: 22,
    happinessGain: 32,
    healthGain: 15,
    drinkingDurationSec: 4,
  },
  {
    id: 'pumpkin_nectar',
    name: 'Тыквенный эликсир',
    description: 'Бархатистый осенний напиток цвета спелой тыквы с капелькой меда.',
    icon: '🎃',
    liquidColor: '#ea580c',
    hungerGain: 16,
    energyGain: 26,
    happinessGain: 24,
    healthGain: 18,
    drinkingDurationSec: 4,
  },
  {
    id: 'mint_tea',
    name: 'Мятный настой',
    description: 'Душистая перечная мята. Снимает стресс и повышает настроение.',
    icon: '🌿',
    liquidColor: '#10b981',
    hungerGain: 4,
    energyGain: 16,
    happinessGain: 25,
    healthGain: 20,
    drinkingDurationSec: 3.5,
  },
  {
    id: 'peach_juice',
    name: 'Персиковый сок',
    description: 'Нежнейший напиток из спелых персиков с сочной бархатной мякотью.',
    icon: '🍑',
    liquidColor: '#fb923c',
    hungerGain: 12,
    energyGain: 24,
    happinessGain: 30,
    healthGain: 14,
    drinkingDurationSec: 4,
  },
  {
    id: 'cherry_nectar',
    name: 'Вишневый нектар',
    description: 'Глубокий рубиновый сок с приятной бодрящей кислинкой.',
    icon: '🍒',
    liquidColor: '#991b1b',
    hungerGain: 10,
    energyGain: 25,
    happinessGain: 28,
    healthGain: 16,
    drinkingDurationSec: 4,
  },
  {
    id: 'citrus_punch',
    name: 'Цитрусовый пунш',
    description: 'Сладкий апельсин с мандарином. Взрыв витамина С!',
    icon: '🍊',
    liquidColor: '#f59e0b',
    hungerGain: 10,
    energyGain: 30,
    happinessGain: 30,
    healthGain: 18,
    drinkingDurationSec: 4,
  },
  {
    id: 'warm_oat_milk',
    name: 'Теплое овсяное молочко',
    description: 'Гипоаллергенное растительное молочко. Нежное лакомство перед сном.',
    icon: '🥛',
    liquidColor: '#f1f5f9',
    hungerGain: 15,
    energyGain: 20,
    happinessGain: 32,
    healthGain: 18,
    drinkingDurationSec: 4,
  },
];
