/**
 * ============================================================================
 * МОДУЛЬ: 20 ДИЗАЙНЕРСКИХ ПАЛИТР И ВЫСОКОДЕТАЛИЗИРОВАННЫЕ СПРАЙТЫ (24x24)
 * ============================================================================
 * 
 * 🎓 ИНТЕРАКТИВНЫЙ УЧЕБНИК: 2X ДЕТАЛИЗАЦИЯ И МАТРИЧНАЯ АНИМАЦИЯ
 * ----------------------------------------------------------------------------
 * 1. ЗАЧЕМ ЭТО НУЖНО (Architectural Reason):
 *    Переход с 16x16 на 24x24 пикселя дает в 2.25 раза больше площади для детализации!
 *    Это позволяет нарисовать:
 *    - Пышную шерстку с трехтоновым затенением (furLight, fur, furDark).
 *    - Детализированные ушки с розовой внутренней раковиной.
 *    - Выразительные глаза с двойным искрящимся бликом.
 *    - Прорисованные усики ('W'), румянец на щечках ('C') и лапки с пальчиками ('P').
 * 
 * 2. СИМВОЛЬНЫЕ КОДЫ СЛОЕВ (24x24 Matrix Format):
 *    '.' = Прозрачный фон
 *    'F' = Основная шерсть (Fur)
 *    'D' = Тень и контур шерсти (Fur Dark)
 *    'L' = Блик и светлый мех (Fur Light)
 *    'B' = Светлое шелковистое брюшко (Belly)
 *    'P' = Розовые ушки, носик и лапки (Pink)
 *    'E' = Черные глазки (Eyes)
 *    'H' = Блик в глазах (Eye Highlight)
 *    'C' = Румяные щечки (Cheeks Blush)
 *    'W' = Усики (Whiskers)
 *    'S' = Семечка / угощение в лапках (Seed/Food)
 * ============================================================================
 */

import { HamsterPalette, FoodItem } from '@/types/hamster';

/**
 * 20 Готовых дизайнерских палитр с трехтоновым затенением меха
 */
export const HAMSTER_PALETTES: HamsterPalette[] = [
  {
    id: 'classic_golden',
    name: 'Золотистый сириец',
    nameEn: 'Classic Golden',
    description: 'Классический пушистый золотисто-рыжий окрас со светлым животиком.',
    fur: '#e69138',
    furDark: '#994d00',
    furLight: '#ffb366',
    belly: '#fff2cc',
    pink: '#f4cccc',
    eyes: '#1b1b1b',
    eyeHighlight: '#ffffff',
    cheeks: '#ea9999',
    paws: '#fce5cd',
  },
  {
    id: 'roborovski_sand',
    name: 'Песочный Роборовского',
    nameEn: 'Roborovski Sand',
    description: 'Нежный песочно-палевый оттенок крошечного пустынного хомячка.',
    fur: '#dfb77c',
    furDark: '#99733e',
    furLight: '#f5d8a8',
    belly: '#fcf6ed',
    pink: '#f8d7da',
    eyes: '#201b15',
    eyeHighlight: '#ffffff',
    cheeks: '#f1b0b7',
    paws: '#fcebe0',
  },
  {
    id: 'albino_snow',
    name: 'Белоснежный альбинос',
    nameEn: 'Albino Snow',
    description: 'Ослепительно белая шубка с редкими рубиново-красными глазками.',
    fur: '#f5f5f5',
    furDark: '#cccccc',
    furLight: '#ffffff',
    belly: '#ffffff',
    pink: '#ffccd5',
    eyes: '#c9184a',
    eyeHighlight: '#ff758f',
    cheeks: '#ffb3c1',
    paws: '#ffe5ec',
  },
  {
    id: 'panda_piebald',
    name: 'Черно-белый панда',
    nameEn: 'Panda Piebald',
    description: 'Контрастный пятнистый окрас с темной маской и белым тельцем.',
    fur: '#2b2d42',
    furDark: '#141521',
    furLight: '#4a4e69',
    belly: '#edf2f4',
    pink: '#ffb5a7',
    eyes: '#0d0d0d',
    eyeHighlight: '#ffffff',
    cheeks: '#fcd5ce',
    paws: '#f8edeb',
  },
  {
    id: 'caramel_cream',
    name: 'Теплый карамельный',
    nameEn: 'Caramel Cream',
    description: 'Аппетитный мягкий оттенок ириски с кремовым подшерстком.',
    fur: '#c68b59',
    furDark: '#7a451d',
    furLight: '#e4ae82',
    belly: '#ffe8d6',
    pink: '#f7cad0',
    eyes: '#301b0f',
    eyeHighlight: '#ffffff',
    cheeks: '#f4acb7',
    paws: '#fed9b7',
  },
  {
    id: 'charcoal_dark',
    name: 'Глубокий угольный',
    nameEn: 'Charcoal Dark',
    description: 'Загадочный антрацитовый окрас с серебристым отливом.',
    fur: '#3a3a3c',
    furDark: '#1a1a1c',
    furLight: '#5a5a5e',
    belly: '#636366',
    pink: '#d8b4b8',
    eyes: '#000000',
    eyeHighlight: '#ffffff',
    cheeks: '#a37081',
    paws: '#8e8e93',
  },
  {
    id: 'cinnamon',
    name: 'Коричный',
    nameEn: 'Cinnamon',
    description: 'Пряный коричневато-медный цвет корицы с бежевым брюшком.',
    fur: '#a0522d',
    furDark: '#5e2609',
    furLight: '#c97548',
    belly: '#f5deb3',
    pink: '#e8b4b8',
    eyes: '#3d1a0a',
    eyeHighlight: '#ffffff',
    cheeks: '#d2828a',
    paws: '#eed9c4',
  },
  {
    id: 'lilac_mist',
    name: 'Дымчато-сиреневый',
    nameEn: 'Lilac Mist',
    description: 'Благородный пепельно-лавандовый оттенок с мягким градиентом.',
    fur: '#9d8189',
    furDark: '#5c464c',
    furLight: '#c2adb3',
    belly: '#f4acb7',
    pink: '#ffcad4',
    eyes: '#2e1f27',
    eyeHighlight: '#ffffff',
    cheeks: '#e07a5f',
    paws: '#ffe5d9',
  },
  {
    id: 'silver_pearl',
    name: 'Серебристый жемчуг',
    nameEn: 'Silver Pearl',
    description: 'Светло-серый шелковистый окрас с мерцающей белой грудкой.',
    fur: '#b8c0c8',
    furDark: '#75808d',
    furLight: '#dde3ea',
    belly: '#f0f4f8',
    pink: '#f9d2dc',
    eyes: '#222831',
    eyeHighlight: '#ffffff',
    cheeks: '#f3abbc',
    paws: '#e9ecef',
  },
  {
    id: 'blue_sapphire',
    name: 'Сапфировый джунгарик',
    nameEn: 'Blue Sapphire',
    description: 'Холодный серо-голубой окрас джунгарского хомячка с темной полоской.',
    fur: '#6c7d93',
    furDark: '#394657',
    furLight: '#94a5bd',
    belly: '#dce4ec',
    pink: '#e6b8c2',
    eyes: '#1a2530',
    eyeHighlight: '#ffffff',
    cheeks: '#d48c9e',
    paws: '#cbd5e1',
  },
  {
    id: 'chocolate_brown',
    name: 'Шоколадный брауни',
    nameEn: 'Chocolate Brown',
    description: 'Глубокий цвет темного шоколада с аппетитной карамельной грудкой.',
    fur: '#5c3a21',
    furDark: '#2e1808',
    furLight: '#855633',
    belly: '#d4a373',
    pink: '#e29578',
    eyes: '#1e0f06',
    eyeHighlight: '#ffffff',
    cheeks: '#dd6b55',
    paws: '#e6ccb2',
  },
  {
    id: 'argente_red',
    name: 'Оранжево-песочный',
    nameEn: 'Argente Red',
    description: 'Яркий персиково-апельсиновый оттенок шерсти с карими глазами.',
    fur: '#e76f51',
    furDark: '#99351d',
    furLight: '#f49d86',
    belly: '#ffe8d6',
    pink: '#f4a261',
    eyes: '#491b1d',
    eyeHighlight: '#ffffff',
    cheeks: '#e9c46a',
    paws: '#f8edeb',
  },
  {
    id: 'honey_gold',
    name: 'Медовый янтарь',
    nameEn: 'Honey Gold',
    description: 'Теплый солнечный янтарно-желтый цвет летнего меда.',
    fur: '#f4a261',
    furDark: '#a8571c',
    furLight: '#ffc594',
    belly: '#fff1d0',
    pink: '#fbc3bc',
    eyes: '#381e05',
    eyeHighlight: '#ffffff',
    cheeks: '#e76f51',
    paws: '#fde8cd',
  },
  {
    id: 'rust_orange',
    name: 'Рыжий кирпичный',
    nameEn: 'Rust Orange',
    description: 'Насыщенный осенний рыжий окрас пушистого зверька.',
    fur: '#d35400',
    furDark: '#7a2d00',
    furLight: '#ff7f2a',
    belly: '#fdebd0',
    pink: '#edbb99',
    eyes: '#2c1200',
    eyeHighlight: '#ffffff',
    cheeks: '#e59866',
    paws: '#fadbd8',
  },
  {
    id: 'dove_grey',
    name: 'Голубино-серый',
    nameEn: 'Dove Grey',
    description: 'Умиротворяющий матовый дымчатый цвет голубиного пера.',
    fur: '#8d99ae',
    furDark: '#4a5363',
    furLight: '#b5c0d3',
    belly: '#edf2f4',
    pink: '#e8b4b8',
    eyes: '#2b2d42',
    eyeHighlight: '#ffffff',
    cheeks: '#d98894',
    paws: '#d8e2dc',
  },
  {
    id: 'mink_soft',
    name: 'Норковый бежевый',
    nameEn: 'Mink Soft',
    description: 'Элегантный бежевый цвет шелковой норки с мягким свечением.',
    fur: '#b79ced',
    furDark: '#6c4baf',
    furLight: '#d8c7ff',
    belly: '#f3ecff',
    pink: '#f8bbd0',
    eyes: '#281a40',
    eyeHighlight: '#ffffff',
    cheeks: '#ea80fc',
    paws: '#ede7f6',
  },
  {
    id: 'copper_glow',
    name: 'Медно-красный',
    nameEn: 'Copper Glow',
    description: 'Сияющий металлический медно-бронзовый цвет шерстки.',
    fur: '#b85d38',
    furDark: '#692b11',
    furLight: '#e0835d',
    belly: '#fad3b8',
    pink: '#e69c8a',
    eyes: '#3b160a',
    eyeHighlight: '#ffffff',
    cheeks: '#cc5a43',
    paws: '#f5c6aa',
  },
  {
    id: 'ivory_white',
    name: 'Слоновая кость',
    nameEn: 'Ivory White',
    description: 'Мягкий благородный сливочно-белый оттенок с темными глазками.',
    fur: '#fefae0',
    furDark: '#b8b082',
    furLight: '#ffffff',
    belly: '#ffffff',
    pink: '#fbc4ab',
    eyes: '#1e1e1e',
    eyeHighlight: '#ffffff',
    cheeks: '#f8ad9d',
    paws: '#faedcd',
  },
  {
    id: 'obsidian_onyx',
    name: 'Глянцевый оникс',
    nameEn: 'Obsidian Onyx',
    description: 'Смоляной черный мех с элегантными белоснежными перчатками на лапках.',
    fur: '#1a1a1e',
    furDark: '#08080a',
    furLight: '#3d3d45',
    belly: '#28282e',
    pink: '#ff9ebb',
    eyes: '#000000',
    eyeHighlight: '#00e5ff',
    cheeks: '#e91e63',
    paws: '#ffffff',
  },
  {
    id: 'cyber_rainbow',
    name: 'Party Cyber / Неон',
    nameEn: 'Party Cyber / Neon',
    description: 'Секретный ретро-киберпанк окрас с неоново-бирюзовой шерсткой и фиолетовыми щечками.',
    fur: '#00f5d4',
    furDark: '#0077b6',
    furLight: '#70fff0',
    belly: '#fee440',
    pink: '#f15bb5',
    eyes: '#9b5de5',
    eyeHighlight: '#ffffff',
    cheeks: '#ff006e',
    paws: '#00f5d4',
  },
];

/**
 * 24x24 Высокодетализированные матрицы анимаций (2x Detail Sprite Sheets)
 */

// 1. Спокойное сидение / IDLE 1 (дыхание, глазки открыты)
export const HAMSTER_24_IDLE_1 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPPFFFFD..DFFFFPPPD',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFFFDFFFFDPPDFFFFDFFFD',
  '.DFFCFDFFFFFFFFFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFFDPDFFFFFFFFD',
  'W..DFFLLBBBBBBBBLLFFD...',
  '...DFFLLBBBBBBBBLLFFD...',
  '...DFFLLBBBBBBBBLLFFD...',
  '...DFFFFBBBBBBBBFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '....DFFDDPPDDFFDDPPD....',
  '.....DPPPPD...DPPPPD....',
  '........................',
  '........................',
  '........................',
];

// 2. Спокойное сидение / IDLE 2 (моргает, ушки шевелятся, носик приподнят)
export const HAMSTER_24_IDLE_2 = [
  '........................',
  '.....DDFFF........FFFDD.',
  '....DPPPFFD......DFFPPPD',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFDDDFFFFFFFFFFFFDDDFD',
  '.DFFFFDFFFFDPPDFFFFDFFFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFDPPDFFFFFFFFD',
  'W..DFFFFFFF.DP.FFFFFFFFD',
  '...DFFLLBBBBBBBBLLFFD...',
  '...DFFLLBBBBBBBBLLFFD...',
  '...DFFLLBBBBBBBBLLFFD...',
  '...DFFFFBBBBBBBBFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '....DFFDDPPDDFFDDPPD....',
  '.....DPPPPD...DPPPPD....',
  '........................',
  '........................',
  '........................',
];

// 3. Ходьба 1 / WALK 1 (передняя правая вперед, задняя левая назад)
export const HAMSTER_24_WALK_1 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFFDPDFFFFFFFFD',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '...DFFD..DFFD..DFFD.....',
  '..DPPPD...DFFD..DPPPD...',
  '..DPPD.....DPPD..DPPD...',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 4. Ходьба 2 / WALK 2 (нейтральная фаза шага)
export const HAMSTER_24_WALK_2 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFFDPDFFFFFFFFD',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '....DFFD....DFFD........',
  '....DPPPD..DPPPD........',
  '.....DPPD...DPPD........',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 5. Ходьба 3 / WALK 3 (передняя левая вперед, задняя правая назад)
export const HAMSTER_24_WALK_3 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFFDPDFFFFFFFFD',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '.....DFFD..DFFD..DFFD...',
  '...DPPPD..DFFD...DPPPD..',
  '...DPPD..DPPD.....DPPD..',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 6. Ходьба 4 / WALK 4 (нейтральная фаза шага 2)
export const HAMSTER_24_WALK_4 = HAMSTER_24_WALK_2;

// 7. Бег в колесе / WHEEL 1 (галоп, лапки вытянуты)
export const HAMSTER_24_WHEEL_1 = [
  '........................',
  '........................',
  '.......DDFFF.....FFFDD..',
  '......DPPPFFD...DFFPPPD.',
  '.....DPPFFFFFFFFFFFFPPD.',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFEEDFFFFFFFFDEEFD...',
  '..DFFEHDFFDPPDFFDEHFD...',
  '..DFFCFDFFDPPDFFDCFFD...',
  '.DFFFFFFFFFDPDFFFFFFFFD.',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '..DPPD.DFFD..DFFD.DPPD..',
  '.DPPPD..DPPD.DPPD..DPPPD',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 8. Бег в колесе / WHEEL 2 (галоп, лапки собраны под тельцем)
export const HAMSTER_24_WHEEL_2 = [
  '........................',
  '........................',
  '........................',
  '.......DDFFF.....FFFDD..',
  '......DPPPFFD...DFFPPPD.',
  '.....DPPFFFFFFFFFFFFPPD.',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFEEDFFFFFFFFDEEFD...',
  '..DFFEHDFFDPPDFFDEHFD...',
  '..DFFCFDFFDPPDFFDCFFD...',
  '.DFFFFFFFFFDPDFFFFFFFFD.',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '.DFFLLBBBBBBBBBBLLFFFD..',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '....DPPDDFFDFFDDPPD.....',
  '....DPPPDDPPDDPPPD......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 9. Умывание / GROOM 1 (лапки у мордочки)
export const HAMSTER_24_GROOM_1 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFDDDFFFFFFFFFFFFDDDFD',
  '.DFFFFDFFFFDPPDFFFFDFFFD',
  '.DFFCFDFFDPPPPPDFFFDCFFD',
  '.DFFCFDFFDPPPPPDFFFDCFFD',
  '..DFFFFFFFDPPDFFFFFFFFD.',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFFFBBBBBBBBBBFFFFD..',
  '...DFFFFFFFFFFFFFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '.....DPPPD....DPPPD.....',
  '......DPPD....DPPD......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 10. Умывание / GROOM 2 (лапки трут ушки)
export const HAMSTER_24_GROOM_2 = [
  '........................',
  '....DPPPDDFFF....FFFDD..',
  '...DPPPDPPPFFD..DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFDDDFFFFFFFFFFFFDDDFD',
  '.DFFFFDFFFFDPPDFFFFDFFFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  '..DFFFFFFFFDPDFFFFFFFFD.',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFFFBBBBBBBBBBFFFFD..',
  '...DFFFFFFFFFFFFFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '.....DPPPD....DPPPD.....',
  '......DPPD....DPPD......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 11. Обнюхивание / SNIFF (мордочка наклонена к опилкам)
export const HAMSTER_24_SNIFF_1 = [
  '........................',
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFFFFFFFFFDEHFD',
  '.DFFCFDFFFFFFFFFFFFDCFFD',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFFFDPPDDPPDFFFFFD...',
  '...DFFFDPPDDPPDFFFFD....',
  '....DFFFFDDPDFFFFFD.....',
  '.....DPPPD....DPPPD.....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 12. Еда / EATING 1 (держит зернышко 'S', щеки надуты)
export const HAMSTER_24_EAT_1 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  'DFFFCCFDFFFDPPDFFFCCFFFD',
  'DFFFCCFDFFSSSSSSFFCCFFFD',
  'DFFFCCFDFFSSSSSSFFCCFFFD',
  '.DFFFFFFDDPPPPPDDFFFFFFD',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFFFBBBBBBBBBBFFFFD..',
  '...DFFFFFFFFFFFFFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '.....DPPPD....DPPPD.....',
  '......DPPD....DPPD......',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 13. Еда / EATING 2 (жует, зернышко меньше)
export const HAMSTER_24_EAT_2 = [
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  'DFFFCCFDFFFDPPDFFFCCFFFD',
  'DFFFCCFDFF.SSSS.FFCCFFFD',
  'DFFFCCFDFF.SSSS.FFCCFFFD',
  '.DFFFFFFDDPPPPPDDFFFFFFD',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFLLBBBBBBBBBBLLFFD..',
  '..DFFFFBBBBBBBBBBFFFFD..',
  '...DFFFFFFFFFFFFFFFFD...',
  '....DFFFFFFFFFFDFFFD....',
  '.....DPPPD....DPPPD.....',
  '......DPPD....DPPD......',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 14. Сон / SLEEP 1 (клубочек выдох)
export const HAMSTER_24_SLEEP_1 = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........DDDDDDDDD.......',
  '.....DDDFFFFFFFFFDDD....',
  '...DDFFFFFFFFFFFFFFFDD..',
  '..DFFFFFFFFFFFFFFFFFFFD.',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFDDPPDFFFFFFFFD',
  '.DFFFFFFFFDDDDFFFFFFFFFD',
  '..DFFLLBBBBBBBBBBLLFFFD.',
  '..DFFLLBBBBBBBBBBLLFFFD.',
  '...DFFFFFFFFFFFFFFFFFD..',
  '.....DDDFFFFFFFFFFDDD...',
  '........DDDDDDDDDD......',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 15. Сон / SLEEP 2 (клубочек вдох - чуть приподнят)
export const HAMSTER_24_SLEEP_2 = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........DDDDDDDDD.......',
  '.....DDDFFFFFFFFFDDD....',
  '...DDFFFFFFFFFFFFFFFDD..',
  '..DFFFFFFFFFFFFFFFFFFFD.',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFDDPPDFFFFFFFFD',
  '.DFFFFFFFFDDDDFFFFFFFFFD',
  '..DFFLLBBBBBBBBBBLLFFFD.',
  '..DFFLLBBBBBBBBBBLLFFFD.',
  '...DFFFFFFFFFFFFFFFFFD..',
  '.....DDDFFFFFFFFFFDDD...',
  '........DDDDDDDDDD......',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 16. Лежит / LAYING
export const HAMSTER_24_LAYING = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  '.DFFFFFFFFFDPDFFFFFFFFFD',
  '.DFFLLBBBBBBBBBBLLFFFFFD',
  '..DPPDFFFFFFFFFFDFFDPPD.',
  '...DPPDDDDDDDDDDDDPPD...',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// 17. Дефекация / POOPING
export const HAMSTER_24_POOPING = [
  '........................',
  '........................',
  '......DDFFF......FFFDD..',
  '.....DPPPFFD....DFFPPPD.',
  '....DPPFFFFFFDDFFFFFFPPD',
  '...DFFFFFFFFFFFFFFFFFFD.',
  '..DFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFF',
  '.DFFEEDFFFFFFFFFFFFDEEFD',
  '.DFFEHDFFFFDPPDFFFFDEHFD',
  '.DFFCFDFFFFDPPDFFFFDCFFD',
  'W.DFFDFFFFFDPPDFFFFFDFFD',
  'WW.DFFFFFFFFDPDFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '.DFFFFFFFFFFFFFFFFFFFFFD',
  '..DFFFFFFFFFFFFFFFFFFD..',
  '...DFFFFFFFFFFFFFFFFD...',
  '....DFFD..DFFD..DFFD....',
  '.....DPPD..DPPD..DPPD...',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// Алиасы обратной совместимости
export const HAMSTER_IDLE_FRAME_1 = HAMSTER_24_IDLE_1;
export const HAMSTER_IDLE_FRAME_2 = HAMSTER_24_IDLE_2;
export const HAMSTER_WALK_FRAME_1 = HAMSTER_24_WALK_1;
export const HAMSTER_WALK_FRAME_2 = HAMSTER_24_WALK_2;
export const HAMSTER_LAYING_FRAME = HAMSTER_24_LAYING;
export const HAMSTER_SLEEP_FRAME_1 = HAMSTER_24_SLEEP_1;
export const HAMSTER_SLEEP_FRAME_2 = HAMSTER_24_SLEEP_2;
export const HAMSTER_EATING_FRAME_1 = HAMSTER_24_EAT_1;
export const HAMSTER_EATING_FRAME_2 = HAMSTER_24_EAT_2;
export const HAMSTER_POOPING_FRAME = HAMSTER_24_POOPING;

/**
 * Меню доступных видов корма
 */
export const FOOD_ITEMS: FoodItem[] = [
  {
    id: 'sunflower_seeds',
    name: 'Семечки подсолнуха',
    description: 'Хрустящее любимое лакомство. Быстро съедается.',
    icon: '🌻',
    hungerGain: 15,
    happinessGain: 10,
    healthGain: 2,
    eatingDurationSec: 3,
  },
  {
    id: 'grain_mix',
    name: 'Зерновая смесь',
    description: 'Овсяные хлопья, просо и пшеница. Сытный сбалансированный обед.',
    icon: '🌾',
    hungerGain: 35,
    happinessGain: 15,
    healthGain: 5,
    eatingDurationSec: 5,
  },
  {
    id: 'apple_slice',
    name: 'Сочное яблоко',
    description: 'Свежий ломтик фрукта. Богат витаминами и отлично поднимает настроение.',
    icon: '🍎',
    hungerGain: 25,
    happinessGain: 25,
    healthGain: 10,
    eatingDurationSec: 4,
  },
  {
    id: 'drops_treat',
    name: 'Йогуртовые дропсы',
    description: 'Царское лакомство для грызунов. Максимальное счастье и целебный эффект!',
    icon: '🍓',
    hungerGain: 45,
    happinessGain: 40,
    healthGain: 20,
    eatingDurationSec: 6,
  },
];
